openapi: 3.0.1
info:
  title: Общение с покупателями
  version: communication
  description: "<div class=\"description_important\">  \n    Узнать больше об общении\
    \ с покупателями можно в <a href=\"https://seller.wildberries.ru/instructions/category/f7f6c465-dd12-422d-80a0-a6d9562115d5?goBackOption=prevRoute&categoryId=30817062-14cc-4a82-bc78-3600c2b0685b\"\
    >справочном центре</a>\n</div>\n\nЧерез методы общения с покупателем вы можете\
    \ работать с:\n  1. [Вопросами](/openapi/user-communication#tag/Voprosy) и [отзывами](/openapi/user-communication#tag/Otzyvy)\
    \ покупателей\n  2. [Шаблонами ответов](/openapi/user-communication#tag/Shablony-otvetov)\
    \ на вопросы и отзывы\n  3. [Чатами с покупателями](/openapi/user-communication#tag/Chat-s-pokupatelyami)\n\
    \  4. [Заявками покупателей на возврат](/openapi/user-communication#tag/Vozvraty-pokupatelyami)\n"
  x-file-name: communications
paths:
  /api/v1/feedbacks/count:
    get:
      security:
      - HeaderApiKey: []
      summary: Количество отзывов
      description: "Метод предоставляет количество обработанных или необработанных\
        \ [отзывов](/openapi/user-communication#tag/Otzyvy/paths/~1api~1v1~1feedbacks/get)\
        \ за заданный период.\n\n<div class=\"description_limit\">  \n  Максимум 1\
        \ запрос в <a href=\"/openapi/api-information#tag/Vvedenie/Limity-zaprosov\"\
        >секунду</a> для всех методов категории <a href=\"/openapi/api-information#tag/Avtorizaciya/Kak-sozdat-token\"\
        >Вопросы и отзывы</a> на один аккаунт продавца.<br>\n  Если превысить лимит\
        \ в 3 запроса в секунду, отправка запросов будет заблокирована на 60 секунд\n\
        </div>\n"
      tags:
      - Отзывы
      parameters:
      - name: dateFrom
        in: query
        description: Дата начала периода в формате Unix timestamp
        schema:
          type: integer
          example: 1688465092
      - name: dateTo
        in: query
        description: Дата конца периода в формате Unix timestamp
        schema:
          type: integer
          example: 1688465092
      - name: isAnswered
        in: query
        description: 'Обработанные отзывы(`true`) или необработанные отзывы(`false`).<br>

          Если не указать, вернутся обработанные отзывы.

          '
        schema:
          type: boolean
          example: false
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: integer
                    description: Количество отзывов
                    example: 724583
                  error:
                    type: boolean
                    description: Есть ли ошибка
                    example: false
                  errorText:
                    type: string
                    description: Описание ошибки
                    example: ''
                  additionalErrors:
                    description: Дополнительные ошибки
                    nullable: true
                    type: array
                    items:
                      type: string
                    example: null
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responsefeedbackErr'
              examples:
                IsAnsweredErr400:
                  $ref: '#/components/examples/IsAnsweredErr400'
                DateFromErr400:
                  $ref: '#/components/examples/DateFromErr400'
                DateToErr400:
                  $ref: '#/components/examples/DateToErr400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responsefeedbackErr'
              examples:
                FeedbackErr403:
                  $ref: '#/components/examples/FeedbackErr403'
        '429':
          $ref: '#/components/responses/429'
components:
  schemas:
    responsefeedbackErr:
      type: object
      properties:
        data:
          type: object
          nullable: true
        error:
          description: Есть ли ошибка
          type: boolean
        errorText:
          description: Описание ошибки
          type: string
        additionalErrors:
          description: Дополнительные ошибки
          nullable: true
          type: array
          items:
            type: string
        requestId:
          description: ''
          type: string
  responses:
    '429':
      description: Слишком много запросов
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: Заголовок ошибки
              detail:
                type: string
                description: Детали ошибки
              code:
                type: string
                description: Внутренний код ошибки
              requestId:
                type: string
                description: Уникальный ID запроса
              origin:
                type: string
                description: ID внутреннего сервиса WB
              status:
                type: number
                description: HTTP статус-код
              statusText:
                type: string
                description: Расшифровка HTTP статус-кода
              timestamp:
                type: string
                format: RFC3339
                description: Дата и время запроса
          example:
            title: too many requests
            detail: limited by c122a060-a7fb-4bb4-abb0-32fd4e18d489
            code: 07e4668e-ac2242c5c8c5-[UK-4dx7JUdskGZ]
            requestId: 9d3c02cc698f8b041c661a7c28bed293
            origin: s2s-api-auth-catalog
            status: 429
            statusText: Too Many Requests
            timestamp: '2024-09-30T06:52:38Z'
    '401':
      description: Пользователь не авторизован
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: Заголовок ошибки
              detail:
                type: string
                description: Детали ошибки
              code:
                type: string
                description: Внутренний код ошибки
              requestId:
                type: string
                description: Уникальный ID запроса
              origin:
                type: string
                description: ID внутреннего сервиса WB
              status:
                type: number
                description: HTTP статус-код
              statusText:
                type: string
                description: Расшифровка HTTP статус-кода
              timestamp:
                type: string
                format: RFC3339
                description: Дата и время запроса
          example:
            title: unauthorized
            detail: 'token problem; token is malformed: could not base64 decode signature:
              illegal base64 data at input byte 84'
            code: 07e4668e--a53a3d31f8b0-[UK-oWaVDUqNrKG]; 03bce=277; 84bd353bf-75
            requestId: 7b80742415072fe8b6b7f7761f1d1211
            origin: s2s-api-auth-catalog
            status: 401
            statusText: Unauthorized
            timestamp: '2024-09-30T06:52:38Z'
  examples:
    DateFromErr400:
      description: Неправильный запрос
      value:
        data: null
        error: true
        errorText: Плохой формат dateFrom
        additionalErrors: null
        requestId: 734c9ea8-39e5-45c9-8cad-f03c13f733e9
    FeedbackErr403:
      description: Доступ запрещён
      value:
        data: null
        error: true
        errorText: Ошибка авторизации
        additionalErrors: null
        requestId: 734c9ea8-39e5-45c9-8cad-f03c13f733e9
    IsAnsweredErr400:
      description: Неправильный запрос
      value:
        data: null
        error: true
        errorText: Плохой формат isAnswered
        additionalErrors: null
        requestId: 734c9ea8-39e5-45c9-8cad-f03c13f733e9
    DateToErr400:
      description: Неправильный запрос
      value:
        data: null
        error: true
        errorText: Плохой формат dateTo
        additionalErrors: null
        requestId: 734c9ea8-39e5-45c9-8cad-f03c13f733e9
